table _Measures
	lineageTag: fea1456a-e9ec-4e6e-9035-9289007e820d

	measure 'Average Value (in Cr.)' =
			
			CALCULATE(AVERAGEX('UPI Data','UPI Data'[Value (in Cr.)]))
		lineageTag: 511cf5e9-3369-421c-a504-4e6915d69e50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reggresion Value' = ```
			
			VAR line = 
			        LINESTX(
			        ALLSELECTED('UPI Data'),
			        'UPI Data'[Value (in Cr.)],
			        'UPI Data'[No. of Banks live on UPI]
			        )
			VAR slope = SELECTCOLUMNS(line, [Slope1])
			VAR intercept = SELECTCOLUMNS(line, [Intercept])
			VAR x = SELECTEDVALUE('UPI Data'[No. of Banks live on UPI])
			VAR y = x*slope + intercept
			RETURN y
			```
		lineageTag: fe1e1a40-f57b-4426-a0fe-e63ee355f23d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Volume (in Cr.)' =
			
			CALCULATE(AVERAGEX('UPI Data','UPI Data'[Volume (in Cr.)]))
		lineageTag: abd379ab-f338-48bc-a1bf-11bcb976ea12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'number of banks added each month' = ```
			
			
			CALCULATE(
			        CLOSINGBALANCEMONTH(SUM('UPI Data'[No. of Banks live on UPI]),'Date Table'[Month]) - 
			        OPENINGBALANCEMONTH(SUM('UPI Data'[No. of Banks live on UPI]),'Date Table'[Month])
			)
			
			```
		formatString: 0
		lineageTag: d1ec3800-c867-4d5b-8f12-9b17bb0c1705

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'number of banks live each month' =
			CALCULATE(
			        CLOSINGBALANCEMONTH(SUM('UPI Data'[No. of Banks live on UPI]),'UPI Data'[Month]) - OPENINGBALANCEMONTH(SUM('UPI Data'[No. of Banks live on UPI]),'UPI Data'[Month])
			)
		formatString: 0.00
		lineageTag: c48da012-21fa-4b6c-9f19-23bdecc12451

	measure 'Regression Volume' = ```
			
			VAR line = 
			        LINESTX(
			        ALLSELECTED('UPI Data'),
			        'UPI Data'[Volume (in Cr.)],
			        'UPI Data'[No. of Banks live on UPI]
			        )
			VAR slope = SELECTCOLUMNS(line, [Slope1])
			VAR intercept = SELECTCOLUMNS(line, [Intercept])
			VAR x = SELECTEDVALUE('UPI Data'[No. of Banks live on UPI])
			VAR y = x*slope + intercept
			RETURN y
			```
		lineageTag: 16b1d5c8-9f34-42e0-8fed-09277160319e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Value Per Transaction' = CALCULATE(DIVIDE(SUM('UPI Data'[Value (in Cr.)]),SUM('UPI Data'[Volume (in Cr.)])))
		formatString: "₹"\ #,0.00;#,0.00\ -"₹";"₹"\ #,0.00
		lineageTag: 04e0025f-2f83-4f31-9f1f-c2db13a8c16c

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Volume (in Cr.) MoM%' = ```
			
			    VAR PrevMonth = CALCULATE(SUM('UPI Data'[Volume (in Cr.)]),PREVIOUSMONTH('Date Table'[Month]))
			    VAR Diff = SUM('UPI Data'[Volume (in Cr.)]) - PrevMonth
			    RETURN
			    DIVIDE(Diff,PrevMonth,BLANK())
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a9f32930-ca45-4adf-a59e-dd7938006a9e

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'Value (in Cr.) MoM%' = ```
			
			    VAR PrevMonth = CALCULATE(SUM('UPI Data'[Value (in Cr.)]),PREVIOUSMONTH('Date Table'[Month]))
			    VAR Diff = SUM('UPI Data'[Value (in Cr.)]) - PrevMonth
			    RETURN
			    DIVIDE(Diff,PrevMonth,BLANK())
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0d871f98-3143-414f-b803-7851d607c0e1

	measure 'Average rate of Value MoM%' = CALCULATE(AVERAGEX('UPI Data',[Value (in Cr.) MoM%]),ALLSELECTED())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 33bf572b-152c-4bc6-96e1-af54accc70bc

	measure 'Average rate of Volume MoM%' = CALCULATE(AVERAGEX('UPI Data',[Volume (in Cr.) MoM%]),ALLSELECTED())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 11dc3a4e-ae4e-4326-a8ec-0cacaaf170c3

	partition _Measures = m
		mode: import
		source =
				let
				    Source = "",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"_Measures"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Text

