table 'UPI Data'
	lineageTag: 785232c1-6156-4626-8580-7eebeff0fcf5

	column Month
		dataType: dateTime
		formatString: dd-mmm-yy
		lineageTag: 67c0ca08-b687-4067-9113-e5dc95c54319
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 6e83e2bb-2995-4fdb-91cf-d6d5d065ed6a
			defaultHierarchy: LocalDateTable_240ff551-4df9-4ad7-9f8d-15bf1235e1df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'No. of Banks live on UPI'
		dataType: int64
		formatString: 0
		lineageTag: ca3472a4-b9ac-40b7-84aa-90ba2eb4e957
		summarizeBy: none
		sourceColumn: No. of Banks live on UPI

		annotation SummarizationSetBy = User

	column 'Volume (in Cr.)'
		dataType: double
		lineageTag: 8897f859-b7f5-42c3-b82b-030b87e40438
		summarizeBy: sum
		sourceColumn: Volume (in Cr.)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Value (in Cr.)'
		dataType: double
		formatString: "₹"\ #,0.00;#,0.00\ -"₹";"₹"\ #,0.00
		lineageTag: 4a9e26b0-cde5-4f0c-ab91-a4ec27f4f67b
		summarizeBy: sum
		sourceColumn: Value (in Cr.)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	partition 'UPI Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\dell5\OneDrive\Desktop\Projects\Power BI Projects\UPI Project\UPI data.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Month", type date}, {"No. of Banks live on UPI", Int64.Type}, {"Volume (in Mn)", type number}, {"Value (in Cr.)", type number}}),
				    #"Calculated End of Month" = Table.TransformColumns(#"Changed Type",{{"Month", Date.EndOfMonth, type date}}),
				    #"Changing Volume to Cr." = Table.TransformColumns(#"Calculated End of Month", {{"Volume (in Mn)", each _ / 10, type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changing Volume to Cr.",{{"Volume (in Mn)", "Volume (in Cr.)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

